export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  VEHICLE_OWNER: 'VEHICLE_OWNER',
  DRIVER: 'DRIVER',
  FLEET_MANAGER: 'FLEET_MANAGER',
  ACCOUNTANT: 'ACCOUNTANT',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];
